#pragma once
#include"ECS.h"
#include"TransformComponent.h"
#include"SpriteComponent.h"
#include"KeyBoardController.h"
#include"ColliderComponent.h"
#include"life.h"
#include"Shot_01.h"
#include"exp_Of_player.h"
#include"lifeOfPlayer.h"
#include"Coin.h"
#include"Shot_02.h"
#include"Shadow.h"
#include"Shot_03.h"
